# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad6661522b2629db43416e7cc4dd34f7b12f3bd790b765906c05ce8e41ab317a630fe5294dead3f1db2c8d21d4f88f6901f275fad7f06a09cad7cb2f97f3eff5

test:
  secret_key_base: 3c11d24bd309d690f700bedea98c28a45b841619b3c464af378aabfe03820dff7796f5204afcb3c138618ea1eb16a41923578a256d1a54e7f5e566736e75e3b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
